// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: temp/src/event/created.proto

package event

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TempCreatedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TempCreatedRequest) Reset() {
	*x = TempCreatedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temp_src_event_created_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TempCreatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempCreatedRequest) ProtoMessage() {}

func (x *TempCreatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_temp_src_event_created_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempCreatedRequest.ProtoReflect.Descriptor instead.
func (*TempCreatedRequest) Descriptor() ([]byte, []int) {
	return file_temp_src_event_created_proto_rawDescGZIP(), []int{0}
}

type TempCreatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TempCreatedResponse) Reset() {
	*x = TempCreatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_temp_src_event_created_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TempCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TempCreatedResponse) ProtoMessage() {}

func (x *TempCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_temp_src_event_created_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TempCreatedResponse.ProtoReflect.Descriptor instead.
func (*TempCreatedResponse) Descriptor() ([]byte, []int) {
	return file_temp_src_event_created_proto_rawDescGZIP(), []int{1}
}

var File_temp_src_event_created_proto protoreflect.FileDescriptor

var file_temp_src_event_created_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x74, 0x65, 0x6d, 0x70, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x74, 0x65, 0x6d, 0x70, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x54, 0x65,
	0x6d, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x15, 0x0a, 0x13, 0x54, 0x65, 0x6d, 0x70, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x69, 0x6c, 0x61, 0x75, 0x32, 0x33, 0x32, 0x38, 0x2f,
	0x67, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_temp_src_event_created_proto_rawDescOnce sync.Once
	file_temp_src_event_created_proto_rawDescData = file_temp_src_event_created_proto_rawDesc
)

func file_temp_src_event_created_proto_rawDescGZIP() []byte {
	file_temp_src_event_created_proto_rawDescOnce.Do(func() {
		file_temp_src_event_created_proto_rawDescData = protoimpl.X.CompressGZIP(file_temp_src_event_created_proto_rawDescData)
	})
	return file_temp_src_event_created_proto_rawDescData
}

var file_temp_src_event_created_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_temp_src_event_created_proto_goTypes = []interface{}{
	(*TempCreatedRequest)(nil),  // 0: temp.event.TempCreatedRequest
	(*TempCreatedResponse)(nil), // 1: temp.event.TempCreatedResponse
}
var file_temp_src_event_created_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_temp_src_event_created_proto_init() }
func file_temp_src_event_created_proto_init() {
	if File_temp_src_event_created_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_temp_src_event_created_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TempCreatedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_temp_src_event_created_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TempCreatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_temp_src_event_created_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temp_src_event_created_proto_goTypes,
		DependencyIndexes: file_temp_src_event_created_proto_depIdxs,
		MessageInfos:      file_temp_src_event_created_proto_msgTypes,
	}.Build()
	File_temp_src_event_created_proto = out.File
	file_temp_src_event_created_proto_rawDesc = nil
	file_temp_src_event_created_proto_goTypes = nil
	file_temp_src_event_created_proto_depIdxs = nil
}
