// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TempCommandServiceClient is the client API for TempCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TempCommandServiceClient interface {
	Find(ctx context.Context, in *FindTempRequest, opts ...grpc.CallOption) (*FindTempResponse, error)
	List(ctx context.Context, in *ListTempRequest, opts ...grpc.CallOption) (*ListTempResponse, error)
}

type tempCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTempCommandServiceClient(cc grpc.ClientConnInterface) TempCommandServiceClient {
	return &tempCommandServiceClient{cc}
}

func (c *tempCommandServiceClient) Find(ctx context.Context, in *FindTempRequest, opts ...grpc.CallOption) (*FindTempResponse, error) {
	out := new(FindTempResponse)
	err := c.cc.Invoke(ctx, "/temp.query.TempCommandService/find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tempCommandServiceClient) List(ctx context.Context, in *ListTempRequest, opts ...grpc.CallOption) (*ListTempResponse, error) {
	out := new(ListTempResponse)
	err := c.cc.Invoke(ctx, "/temp.query.TempCommandService/list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TempCommandServiceServer is the server API for TempCommandService service.
// All implementations must embed UnimplementedTempCommandServiceServer
// for forward compatibility
type TempCommandServiceServer interface {
	Find(context.Context, *FindTempRequest) (*FindTempResponse, error)
	List(context.Context, *ListTempRequest) (*ListTempResponse, error)
	mustEmbedUnimplementedTempCommandServiceServer()
}

// UnimplementedTempCommandServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTempCommandServiceServer struct {
}

func (UnimplementedTempCommandServiceServer) Find(context.Context, *FindTempRequest) (*FindTempResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedTempCommandServiceServer) List(context.Context, *ListTempRequest) (*ListTempResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedTempCommandServiceServer) mustEmbedUnimplementedTempCommandServiceServer() {}

// UnsafeTempCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TempCommandServiceServer will
// result in compilation errors.
type UnsafeTempCommandServiceServer interface {
	mustEmbedUnimplementedTempCommandServiceServer()
}

func RegisterTempCommandServiceServer(s *grpc.Server, srv TempCommandServiceServer) {
	s.RegisterService(&_TempCommandService_serviceDesc, srv)
}

func _TempCommandService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindTempRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempCommandServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temp.query.TempCommandService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempCommandServiceServer).Find(ctx, req.(*FindTempRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TempCommandService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTempRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TempCommandServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temp.query.TempCommandService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TempCommandServiceServer).List(ctx, req.(*ListTempRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TempCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "temp.query.TempCommandService",
	HandlerType: (*TempCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "find",
			Handler:    _TempCommandService_Find_Handler,
		},
		{
			MethodName: "list",
			Handler:    _TempCommandService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temp/src/query/service.proto",
}
