// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: proto/src/query/find.proto

package query

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FindProtoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindProtoRequest) Reset() {
	*x = FindProtoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_src_query_find_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProtoRequest) ProtoMessage() {}

func (x *FindProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_query_find_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProtoRequest.ProtoReflect.Descriptor instead.
func (*FindProtoRequest) Descriptor() ([]byte, []int) {
	return file_proto_src_query_find_proto_rawDescGZIP(), []int{0}
}

type FindProtoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindProtoResponse) Reset() {
	*x = FindProtoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_src_query_find_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindProtoResponse) ProtoMessage() {}

func (x *FindProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_query_find_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindProtoResponse.ProtoReflect.Descriptor instead.
func (*FindProtoResponse) Descriptor() ([]byte, []int) {
	return file_proto_src_query_find_proto_rawDescGZIP(), []int{1}
}

var File_proto_src_query_find_proto protoreflect.FileDescriptor

var file_proto_src_query_find_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x2f, 0x66, 0x69, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x12, 0x0a, 0x10, 0x46, 0x69, 0x6e,
	0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a,
	0x11, 0x46, 0x69, 0x6e, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x74, 0x69, 0x6c, 0x61, 0x75, 0x32, 0x33, 0x32, 0x38, 0x2f, 0x67, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_src_query_find_proto_rawDescOnce sync.Once
	file_proto_src_query_find_proto_rawDescData = file_proto_src_query_find_proto_rawDesc
)

func file_proto_src_query_find_proto_rawDescGZIP() []byte {
	file_proto_src_query_find_proto_rawDescOnce.Do(func() {
		file_proto_src_query_find_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_src_query_find_proto_rawDescData)
	})
	return file_proto_src_query_find_proto_rawDescData
}

var file_proto_src_query_find_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_src_query_find_proto_goTypes = []interface{}{
	(*FindProtoRequest)(nil),  // 0: proto.query.FindProtoRequest
	(*FindProtoResponse)(nil), // 1: proto.query.FindProtoResponse
}
var file_proto_src_query_find_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_src_query_find_proto_init() }
func file_proto_src_query_find_proto_init() {
	if File_proto_src_query_find_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_src_query_find_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindProtoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_src_query_find_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindProtoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_src_query_find_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_src_query_find_proto_goTypes,
		DependencyIndexes: file_proto_src_query_find_proto_depIdxs,
		MessageInfos:      file_proto_src_query_find_proto_msgTypes,
	}.Build()
	File_proto_src_query_find_proto = out.File
	file_proto_src_query_find_proto_rawDesc = nil
	file_proto_src_query_find_proto_goTypes = nil
	file_proto_src_query_find_proto_depIdxs = nil
}
