// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ProtoCommandServiceClient is the client API for ProtoCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoCommandServiceClient interface {
	Find(ctx context.Context, in *FindProtoRequest, opts ...grpc.CallOption) (*FindProtoResponse, error)
	List(ctx context.Context, in *ListProtoRequest, opts ...grpc.CallOption) (*ListProtoResponse, error)
}

type protoCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoCommandServiceClient(cc grpc.ClientConnInterface) ProtoCommandServiceClient {
	return &protoCommandServiceClient{cc}
}

func (c *protoCommandServiceClient) Find(ctx context.Context, in *FindProtoRequest, opts ...grpc.CallOption) (*FindProtoResponse, error) {
	out := new(FindProtoResponse)
	err := c.cc.Invoke(ctx, "/proto.query.ProtoCommandService/find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoCommandServiceClient) List(ctx context.Context, in *ListProtoRequest, opts ...grpc.CallOption) (*ListProtoResponse, error) {
	out := new(ListProtoResponse)
	err := c.cc.Invoke(ctx, "/proto.query.ProtoCommandService/list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoCommandServiceServer is the server API for ProtoCommandService service.
// All implementations must embed UnimplementedProtoCommandServiceServer
// for forward compatibility
type ProtoCommandServiceServer interface {
	Find(context.Context, *FindProtoRequest) (*FindProtoResponse, error)
	List(context.Context, *ListProtoRequest) (*ListProtoResponse, error)
	mustEmbedUnimplementedProtoCommandServiceServer()
}

// UnimplementedProtoCommandServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProtoCommandServiceServer struct {
}

func (UnimplementedProtoCommandServiceServer) Find(context.Context, *FindProtoRequest) (*FindProtoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}
func (UnimplementedProtoCommandServiceServer) List(context.Context, *ListProtoRequest) (*ListProtoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedProtoCommandServiceServer) mustEmbedUnimplementedProtoCommandServiceServer() {}

// UnsafeProtoCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoCommandServiceServer will
// result in compilation errors.
type UnsafeProtoCommandServiceServer interface {
	mustEmbedUnimplementedProtoCommandServiceServer()
}

func RegisterProtoCommandServiceServer(s *grpc.Server, srv ProtoCommandServiceServer) {
	s.RegisterService(&_ProtoCommandService_serviceDesc, srv)
}

func _ProtoCommandService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoCommandServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.query.ProtoCommandService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoCommandServiceServer).Find(ctx, req.(*FindProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoCommandService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProtoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoCommandServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.query.ProtoCommandService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoCommandServiceServer).List(ctx, req.(*ListProtoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProtoCommandService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.query.ProtoCommandService",
	HandlerType: (*ProtoCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "find",
			Handler:    _ProtoCommandService_Find_Handler,
		},
		{
			MethodName: "list",
			Handler:    _ProtoCommandService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/src/query/service.proto",
}
